---
title: "Data preprocessing"
output: html_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
library(tidyverse)
library(dplyr)
```


```{r}
# Need to run this chunk all at once

setwd("~/Desktop/BIOST 2069/BIOST_2069/GSE167536")

mouse_counts <- read.delim("GSE167536_mouseLPS_rawcounts.txt", header = TRUE, sep = ",")

hum_counts <- read.delim("GSE167536_humanstress_rawcounts.txt", header = TRUE, sep = ",")

# import sample data
mouse_colData <- read_excel("Sample data.xlsx", 
     sheet = "Mouse")
hum_colData <- read_excel("Sample data.xlsx", 
     sheet = "Human")
```

```{r}
head(mouse_counts)
head(mouse_colData)
head(hum_counts)
head(hum_colData)
```

```{r}
# making sure the row names in colData matches to column names in counts_data
all(colnames(mouse_counts) %in% rownames(mouse_colData)) #FALSE
mouse_counts <- mouse_counts %>% column_to_rownames(var = "X")
mouse_colData <- mouse_colData %>% column_to_rownames(var = "pool")
all(colnames(mouse_counts) %in% rownames(mouse_colData)) #TRUE now

hum_counts <- hum_counts %>% column_to_rownames(var = "gene")
hum_colData <- hum_colData %>% column_to_rownames(var = "id")
all(colnames(hum_counts) %in% rownames(hum_colData)) #TRUE

# are they in the same order?
all(colnames(mouse_counts) == rownames(mouse_colData))
all(colnames(hum_counts) == rownames(hum_colData)) # FALSE
new_order = sort(colnames(hum_counts))
hum_counts<- hum_counts[,new_order]
all(colnames(hum_counts) == rownames(hum_colData))
```

```{r}
# construct DESEQ object

mouse_dds <- DESeqDataSetFromMatrix(countData = mouse_counts,
                       colData = mouse_colData,
                       design = ~ treatment + chronicStress)
#According to the paper, they also corrected for batch effects from the pool... not sure about that so did not include

#design is treatment+chronicStress because we want to perform WALD on stress, regressing out LPS. This is what it states in paper.

hum_dds <- DESeqDataSetFromMatrix(countData = hum_counts,
                       colData = hum_colData,
                       design = ~ stress)
#According to the paper, they also corrected for myocardialinfarction status but we don't have that data?

# pre-filtering: removing rows with low gene counts
# keeping rows that have at least 10 reads total
# The paper filtered this way: Only genes with a CPM (counts per million) > 5 in at least 2 samples were included. I fee; like this way is pretty much the same.

keep <- rowSums(counts(mouse_dds)) >= 10
mouse_dds <- mouse_dds[keep,]

keep <- rowSums(counts(hum_dds)) >= 10
hum_dds <- hum_dds[keep,]

# set the factor level
mouse_dds$treatment <- relevel(mouse_dds$treatment, ref = "untreated")
mouse_dds$chronicStress <- relevel(mouse_dds$chronicStress, ref = "control")
hum_dds$stress <- relevel(hum_dds$stress, ref = "low")

```

```{r}
# Run Deseq

mouse_dds <- DESeq(mouse_dds)
hum_dds <- DESeq(hum_dds)

mouse_res <- results(mouse_dds)
summary(mouse_res)
mouse_res0.01 <- results(mouse_dds, alpha = 0.01)
summary(mouse_res0.01)

hum_res <- results(hum_dds)
hum_res0.01 <- results(hum_dds, alpha = 0.01)
summary(hum_res0.01)

#I'm not getting very many DEGs compared to the paper...
```

```{r}
plotMA(mouse_res)
plotMA(hum_res)
```
